apiVersion: v1
kind: Service
metadata:
  name: postgres-mcp
  namespace: mcp-lab
spec:
  selector:
    app: postgres-mcp
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mcp
  namespace: mcp-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mcp
  template:
    metadata:
      labels:
        app: postgres-mcp
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "aiagent"
            - name: POSTGRES_PASSWORD
              value: "aiagentpass"
            - name: POSTGRES_DB
              value: "mcpaudit"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
