apiVersion: v1
kind: Service
metadata:
  name: ai-lab-paid
  namespace: ai-ml-lab
  labels:
    app: ai-lab-paid
spec:
  type: ClusterIP
  selector:
    app: ai-lab-paid
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
