apiVersion: v1
kind: Service
metadata:
  name: paid-agent-lab-4-1
  namespace: ai-ml-lab-4-1-paid
spec:
  type: ClusterIP
  selector:
    app: paid-agent-lab-4-1
  ports:
    - port: 8000
      targetPort: 8000
