apiVersion: v1
kind: Service
metadata:
  name: ai-lab-2-1-paid
  namespace: ai-ml-lab-2-1
  labels:
    app: ai-lab-2-1-paid
spec:
  type: ClusterIP
  selector:
    app: ai-lab-2-1-paid
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
