apiVersion: batch/v1
kind: Job
metadata:
  name: batch-inference-paid-once
  namespace: ai-ml-lab-3-1-paid
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: batch-inference-paid
    spec:
      restartPolicy: Never
      containers:
        - name: batch-inference
          image: ai-lab-3-1-paid:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: CPU_BURN_MS
              value: "20"
            - name: COST_PER_1K_PRED
              value: "0.002"
