apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-lab-2-2-paid
  namespace: ai-ml-lab-2-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-lab-2-2-paid
  template:
    metadata:
      labels:
        app: ai-lab-2-2-paid
    spec:
      containers:
        - name: ai-lab-2-2-paid
          image: ai-lab-2-2-paid:v1
          ports:
            - containerPort: 9000
          env:
            - name: APP_ENV
              value: "kubernetes"
            - name: CPU_BURN_MS
              value: "40"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
