apiVersion: v1
kind: Service
metadata:
  name: ai-lab-2-2-paid
  namespace: ai-ml-lab-2-2
spec:
  type: ClusterIP
  selector:
    app: ai-lab-2-2-paid
  ports:
    - port: 9000
      targetPort: 9000
